// <auto-generated />
using System;
using Fip.Persistence.Context;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace Fip.Persistence.Migrations
{
    [DbContext(typeof(FipDbContext))]
    partial class FipDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.9")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("Fip.Persistence.Entities.FlightEntity", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uniqueidentifier");

                    b.Property<double?>("ArrivalLatitude")
                        .HasColumnType("float");

                    b.Property<double?>("ArrivalLongitude")
                        .HasColumnType("float");

                    b.Property<string>("Callsign")
                        .HasMaxLength(8)
                        .HasColumnType("nvarchar(8)");

                    b.Property<double?>("DepartureLatitude")
                        .HasColumnType("float");

                    b.Property<double?>("DepartureLongitude")
                        .HasColumnType("float");

                    b.Property<DateTimeOffset>("EndTime")
                        .HasColumnType("datetimeoffset");

                    b.Property<string>("Icao24")
                        .IsRequired()
                        .HasMaxLength(6)
                        .HasColumnType("nvarchar(6)");

                    b.Property<double?>("MaximumAltitudeFeet")
                        .HasColumnType("float");

                    b.Property<DateTimeOffset>("StartTime")
                        .HasColumnType("datetimeoffset");

                    b.HasKey("Id");

                    b.HasIndex("Callsign")
                        .HasDatabaseName("IX_Flights_Callsign");

                    b.HasIndex("EndTime")
                        .HasDatabaseName("IX_Flights_EndTime");

                    b.HasIndex("Icao24")
                        .HasDatabaseName("IX_Flights_Icao24");

                    b.HasIndex("Icao24", "StartTime", "EndTime")
                        .HasDatabaseName("IX_Flights_Icao24_StartTime_EndTime");

                    b.HasIndex("StartTime")
                        .HasDatabaseName("IX_Flights_StartTime");

                    b.ToTable("Flights", (string)null);
                });

            modelBuilder.Entity("Fip.Persistence.Entities.FlightEventEntity", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uniqueidentifier");

                    b.Property<double?>("AltitudeFeet")
                        .HasColumnType("float");

                    b.Property<string>("Description")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<Guid>("FlightId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<double?>("Latitude")
                        .HasColumnType("float");

                    b.Property<double?>("Longitude")
                        .HasColumnType("float");

                    b.Property<DateTimeOffset>("Timestamp")
                        .HasColumnType("datetimeoffset");

                    b.Property<string>("Type")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("nvarchar(32)");

                    b.HasKey("Id");

                    b.HasIndex("FlightId", "Timestamp")
                        .HasDatabaseName("IX_FlightEvents_FlightId_Timestamp");

                    b.ToTable("FlightEvents", (string)null);
                });

            modelBuilder.Entity("Fip.Persistence.Entities.FlightTelemetryPointEntity", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uniqueidentifier");

                    b.Property<double?>("AltitudeFeet")
                        .HasColumnType("float");

                    b.Property<string>("Callsign")
                        .HasMaxLength(8)
                        .HasColumnType("nvarchar(8)");

                    b.Property<Guid>("FlightId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<double?>("GroundSpeedKnots")
                        .HasColumnType("float");

                    b.Property<string>("Icao24")
                        .IsRequired()
                        .HasMaxLength(6)
                        .HasColumnType("nvarchar(6)");

                    b.Property<double?>("Latitude")
                        .HasColumnType("float");

                    b.Property<double?>("Longitude")
                        .HasColumnType("float");

                    b.Property<DateTimeOffset>("Timestamp")
                        .HasColumnType("datetimeoffset");

                    b.Property<double?>("TrackDegrees")
                        .HasColumnType("float");

                    b.Property<double?>("VerticalRateFeetPerMinute")
                        .HasColumnType("float");

                    b.HasKey("Id");

                    b.HasIndex("FlightId", "Timestamp")
                        .HasDatabaseName("IX_FlightTelemetryPoints_FlightId_Timestamp");

                    b.ToTable("FlightTelemetryPoints", (string)null);
                });

            modelBuilder.Entity("Fip.Persistence.Entities.FlightEventEntity", b =>
                {
                    b.HasOne("Fip.Persistence.Entities.FlightEntity", "Flight")
                        .WithMany("Events")
                        .HasForeignKey("FlightId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Flight");
                });

            modelBuilder.Entity("Fip.Persistence.Entities.FlightTelemetryPointEntity", b =>
                {
                    b.HasOne("Fip.Persistence.Entities.FlightEntity", "Flight")
                        .WithMany("TelemetryPoints")
                        .HasForeignKey("FlightId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Flight");
                });

            modelBuilder.Entity("Fip.Persistence.Entities.FlightEntity", b =>
                {
                    b.Navigation("Events");

                    b.Navigation("TelemetryPoints");
                });
#pragma warning restore 612, 618
        }
    }
}
